stages:
  - test

test:php8.0:
  image: cimg/php:8.0.11
  stage: test
  cache:
    # this expands to the branch, eg: 'master'
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - vendor/
  script:
  - composer install
  - composer dev:qa
