<?php

declare(strict_types=1);

namespace TimDev\Test\Log\Support;

use Monolog\Formatter\NormalizerFormatter;
use TimDev\Log\JsonFormatter;
use TimDev\StackLogger\Test\Support\TestLoggerTrait;

class TestJsonFormatter extends JsonFormatter
{
    public function format(array $record): string
    {
        return parent::format($record); // TODO: Change the autogenerated stub
    }


}
